### ISSUE TITLE
Flutter: Clicking on Empty area should Close keyboard (login/signup)

### ISSUE THREAD

**Issue by AmanNegi** [AmanNegi/AgroMillets#13]
# Issue
Can not dismiss keyboard in login/signup pages once opened. 

# Possible Solution
Cover the entire login/signup pages with `GestureDetector` and using `FocusScope` remove focus from the text fields.

Here's a blog as reference: https://flutterigniter.com/dismiss-keyboard-form-lose-focus/

**Comment by gantanikhilraj** [comment]
I want to work on this issue. please assign it to me.
