### ISSUE TITLE
[flutter] Change Project version

### ISSUE THREAD

**Issue by AmanNegi** [AmanNegi/AgroMillets#17]
Change app version to `0.0.1`.

Here's the file to edit:
https://github.com/AmanNegi/AgroMillets/blob/main/frontend/flutter/agro_millets/pubspec.yaml#L19

**Comment by gantanikhilraj** [comment]
I would like to work on this, please assign it to me.

**Comment by AmanNegi** [comment]
@gantanikhilraj this task is already assigned. We would love to have your help. If you're intrested in contributing you can check #21
