### ISSUE TITLE
[docs] Need help with React Part of Application

### ISSUE THREAD

**Issue by AmanNegi** [AmanNegi/AgroMillets#23]
Currently, we use a generic documentation template in `frontend/react/README.md`. It would be better if we mentioned real-world documentation that would involve the following:

- Forking and Cloning the project.
- Installing Nodejs.
- Scripts that can be used to run the app (Can be found in `fontend/react/agro-millets/package.json`.

**Comment by realrohitgurav** [comment]
Can you assign this to me? @AmanNegi

**Comment by AmanNegi** [comment]
Sure best of luck!

**Comment by AmanNegi** [comment]
@realrohitgurav the documentation looks fine, but the indentation is skewed. Could you please fix this issue?

![image](https://user-images.githubusercontent.com/37607224/229062708-b2bd9443-43ec-4afd-9992-70aef1625302.png)
