### ISSUE TITLE
[docs] Update URL in Readme.md

### ISSUE THREAD

**Issue by AmanNegi** [AmanNegi/AgroMillets#24]
# Issue

We recently updated our documentation folder from `doc` to `docs` in #14. This invalidates the path of some links provided in `Readme.md`. We require you to update the URL to the valid path.

(PS: The `Contribute to AgroMillets` link is invalid)

**Comment by munnokd** [comment]
Can I work on this issue?

**Comment by AmanNegi** [comment]
Sure!
