### ISSUE TITLE
Update the README.md

### ISSUE THREAD

**Issue by the-amazing-atharva** [AmanNegi/AgroMillets#29]
Hi!!

I would like to work on the README.md of this project to make it more appealing by adding badges, emojis, restructuring etc

I would like to be assigned if approved!

**Comment by AmanNegi** [comment]
Hello, Sure we would love that! If possible could you also add the list of contributors at the end just like it's done [here](https://github.com/AppFlowy-IO/AppFlowy#join-the-community-to-build-appflowy-together)?

**Comment by the-amazing-atharva** [comment]
Sure!!

Working on it soon

**Comment by the-amazing-atharva** [comment]
1. Could you paste the link to the website/app here so that I can add it in the repo
2. I was browsing good first issues/ help wanted/ documentation issues on github

**Comment by AmanNegi** [comment]
Currently we have not deployed the application anywhere, for now you can place template links. 

For react we will possibly host to netlify at the moment and for Android we will provide a release APK in the repository itself.
