### ISSUE TITLE
[doc] Add End User Products to Documentation

### ISSUE THREAD

**Issue by AmanNegi** [AmanNegi/AgroMillets#47]
# Modification Required 

We have now deployed our website. We need to add it to the documentation so that end users can access our platform.

## Resources

Website: https://agro-millets.netlify.app/
App: Mentioned under Releases

**Comment by munnokd** [comment]
Hey @AmanNegi can you assign this issue to me?

**Comment by AmanNegi** [comment]
Sure, let me know if you have any queries.

**Comment by munnokd** [comment]
Thank you @AmanNegi for assigning this issue to me.
