### ISSUE TITLE
[docs] Add General code of conduct 

### ISSUE THREAD

**Issue by AmanNegi** [AmanNegi/AgroMillets#66]
Currently, we are missing a `CODE_OF_CONDUCT.md` file in our repository. If you are new to open source and don't know about the code of conduct you may check [this](https://opensource.guide/code-of-conduct/).

## Helpful References:
- https://github.com/AppFlowy-IO/AppFlowy/blob/main/CODE_OF_CONDUCT.md
- https://github.com/flutter/flutter/blob/master/CODE_OF_CONDUCT.md

You can basically find it in every open source project, which allows contributors to contribute.

**Comment by amelia2802** [comment]
Hi, there @AmanNegi ,
I'm interested in working on this issue!

**Comment by AmanNegi** [comment]
Great I'll assign this to you, best of luck 😊

**Comment by aadarsh10c** [comment]
Hi, @AmanNegi , I'm intrested in working on the issue.

**Comment by AmanNegi** [comment]
Hey @aadarsh10c, someone is already working on this task.
