### ISSUE TITLE
[docs] Improve Live Preview Section

### ISSUE THREAD

**Issue by AmanNegi** [AmanNegi/AgroMillets#68]
In the text under the Live Preview section, check alternatives for displaying Preview links. Which should at least ensure that the text is readable.

![image](https://user-images.githubusercontent.com/37607224/233631167-5659945f-fcbc-458a-955b-2dc0cde65602.png)

**Comment by Subham5401** [comment]
Hi,
I'm interested in taking this opportunity. Could you please provide me with the specific details or requirements necessary to proceed further? Thank you!

**Comment by AmanNegi** [comment]
Hey @Subham5401, you can work on this issue. Basically, as you can see the links are not easily readable, I have attached the image above. Now it's up to your creativity to either simply make it a normal link and remove the code styling or use some badges there.

**Comment by Subham5401** [comment]
Thank you for providing the additional information. I will proceed with incorporating it into the task at hand.

**Comment by AmanNegi** [comment]
Thanks a lot for contributing 🌟
